### PR TITLE
chore: use ruff format instead of black

### PR DESCRIPTION
**Pull request by henryiii**
This is faster and simpler, doesn't require a separate install.

### CODE REVIEW

**Review by eduardo-rodrigues — APPROVED** [review]

**Comment by henryiii** [comment]
I missed adding notebooks, can do that in a sec.

**Comment by eduardo-rodrigues** [comment]
> I missed adding notebooks, can do that in a sec.

Advance thanks :).

**Review by eduardo-rodrigues — APPROVED** [review]
Feel free to merge when happy.

**Comment by henryiii** [comment]
Added ruff linting to the notebooks too.

**Pull request merged**
