### PR TITLE
feat: drop Python 2

### PR DESCRIPTION
**Pull request by henryiii**
Removes Python 2 and 3.5 support.

- chore: bump pre-commit
- chore: pre-commit py3
- style: autofixes
- style: manual fixes
- chore: drop six
- chore: drop py2 backports
- tests: use pyproject config, pytest 6+

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Wow, that was fast! Did you use any semi-automation for all this?

I will look asap but right now is tricky ...

**Comment by henryiii** [comment]
I used pyupgrade (and the other tools); most of the manual work was actually from adding spell checking, which surfaced quite a few typos. I also manually dropped the backports and six, moved to pytest 6, and bumped the CI for Python 3.10.

**Comment by henryiii** [comment]
I looked into automation for adding basic type hints (pytest-monkeytype), but will wait to put that in till after this goes in.

**Review by eduardo-rodrigues — APPROVED** [review]
Nice 👍!

**Pull request merged**
