### PR TITLE
Adapt to Python 3 only Lark 1.x

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Closes https://github.com/scikit-hep/decaylanguage/issues/280.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
This is a no-brainer and fixes Python 3.11 without a need for a hack. Clean.

Any comments @henryiii? Else approve just so I know you're happy as well :-).

**Comment by henryiii** [comment]
> fixes Python 3.11 without a need for a hack


Is something broken on Python 3.11?

**Comment by eduardo-rodrigues** [comment]
> > fixes Python 3.11 without a need for a hack
> 
> Is something broken on Python 3.11?

The CI tests were failing on 3.11 with recent PRs because of a deprecation warning, see https://github.com/scikit-hep/decaylanguage/actions/runs/3393703868/jobs/5641353853. A fix would require a minor release in Lark for the o.x series. I then realised that the fix got implemented in the 1.x series and decided to go "2-in-1" simply trying to move to Lark 1.x :-).

**Comment by henryiii** [comment]
Ahh, okay, yes, I remember that warning.

**Comment by eduardo-rodrigues** [comment]
I will try and release DecayLanguage asap since Particle and DecayLanguage both have great updates in, for Belle II colleagues and cosmics!

**Pull request merged**
