### PR TITLE
Adding Azure

### PR DESCRIPTION
**Pull request by henryiii**
This is a first draft of an azure build.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Nice that you went ahead and created this PR.

**Comment by eduardo-rodrigues** [comment]
The Azure build fined OK :-). You can merge this in!

**Comment by eduardo-rodrigues** [comment]
BTW, I've added you as project admin on Azure DevOps.

**Comment by henryiii** [comment]
Could you add the badge, too?

**Comment by eduardo-rodrigues** [comment]
I hope I got the badges right.

We will now have many badges. Some will be removed once Travis is switched off ...

**Comment by eduardo-rodrigues** [comment]
I committed directly to master a trivial "definitionId" number change in Azure links and now coverage and tests info are properly shown in the README.

**Pull request merged**
