### PR TITLE
Fixed bug in print_decay_modes where decays with equal BFs were skipped

### LINKED ISSUE #451: `MyDecFileParser.print_decay_modes` ommits decays if BF is equal to others
When printing a .dec file such as
```
Decay B0sig
0.01    MyD*-    MyD_s+   pi0                    PHOTOS  ISGW2;
0.01    MyD*-    MyD_s+   pi+  pi-               PHOTOS  ISGW2;
0.01    MyD*-    MyD_s*+  pi+  pi-               PHOTOS  ISGW2;

0.001  MyD_2*-  MyD_s*+  pi0  pi0               PHOTOS  ISGW2;
0.001  MyD_2*-  MyD_s+   pi+  pi-               PHOTOS  ISGW2;
0.001  MyD_2*-  MyD_s*+  pi+  pi-               PHOTOS  ISGW2;
Enddecay
End
```

with the code

```
    parser = MyDecFileParser(dec_file)
    parser.parse()

    decays = list_complement(parser.list_decay_mother_names(),
                             parser.list_charge_conjugate_decays())

    for d in decays:
        print('Decay {}'.format(d))
        parser.print_decay_modes(d)
```

you get
```
Decay B0sig
  0.9090909091      MyD*-   MyD_s*+ pi+ pi-     PHOTOS ISGW2;
  0.09090909091     MyD_2*- MyD_s*+ pi+ pi-     PHOTOS ISGW2;
```

Trying different things, I found out that this is because, when there are several decays with the same BF, it only prints the last one.

### PR DESCRIPTION
**Pull request by manuelfs**
This PR fixes #451. 

I also reduced the number of decimals printed to 5 or 7.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi @manuelfs, thank you for the fix. I'm sure you tested it but one still needs to add a test to ensure all is fine. Will you take care of that? And also of fixing the pre-commit failure? (I'm not sure I will have time before I depart on holidays. Otherwise I will get back to this upon return.)

**Comment by manuelfs** [comment]
There was already a "test" of the `print_decay_modes` function, though it cannot fail as it only prints. I added a new function to print a more complete .dec file where you would have seen the bug, but I don't think it would be easy to `assert` a condition for this printing function.

I don't know how to handle the error in the pre-commit check, I don't see that in my system. Also, I get a super long traceback when I try to run `nox`...
```
...
nox > pylint src
PYLINTHOME is now '/Users/manuelf/Library/Caches/pylint' but obsolescent '/Users/manuelf/.pylint.d' is found; you can safely remove the latter
Exception on node <ImportFrom l.5 at 0x10e282210> in file '/Users/manuelf/code/decaylanguage/src/decaylanguage/_version.py'
Traceback (most recent call last):
  File "/Users/manuelf/code/decaylanguage/.nox/pylint/lib/python3.12/site-packages/pylint/checkers/imports.py", line 798, in _get_imported_module
    return importnode.do_import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manuelf/code/decaylanguage/.nox/pylint/lib/python3.12/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manuelf/code/decaylanguage/.nox/pylint/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manuelf/code/decaylanguage/.nox/pylint/lib/python3.12/site-packages/astroid/manager.py", line 232, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manuelf/code/decaylanguage/.nox/pylint/lib/python3.12/site-packages/astroid/manager.py", line 124, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manuelf/code/decaylanguage/.nox/pylint/lib/python3.12/site-packages/astroid/builder.py", line 144, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manuelf/code/decaylanguage/.nox/pylint/lib/python3.12/site-packages/astroid/builder.py", line 204, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manuelf/code/decaylanguage/.nox/pylint/lib/python3.12/site-packages/astroid/rebuilder.py", line 254, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manuelf/code/decaylanguage/.nox/pylint/lib/python3.12/site-packages/astroid/rebuilder.py", line 603, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'
...
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
astroid.exceptions.AstroidError
nox > Command pylint src failed with exit code 1
nox > Session pylint failed.
nox > Running session tests-3.7

```

**Comment by eduardo-rodrigues** [comment]
Hi @manuelfs. I'm back and am going to take a look ...

Can you commit your custom test file to get rid of the error
```
test_custom_model_name

FileNotFoundError: '../data/test_custom_decay_model.dec'!
```
and actually test things?

I don't use nox (yet), sorry.

**Comment by eduardo-rodrigues** [comment]
Never mind, the file is there !

**Comment by eduardo-rodrigues** [comment]
Let me know if you are also happy with this new version of the PR.

**Comment by eduardo-rodrigues** [comment]
The update
```
-        "MyRho0": {"mass": 0.8, "width": 149.1},
+        "MyRho0": {"mass": 0.8, "width": 147.4},
```
hints at a bug upon starring a bit more at why this is updated. As I would like to address that asap and I'm unsure if you are away on holidays, I will go ahead and merge this. Kindly follow-up if you see a need.

Thank you for this contribution.

**Review by eduardo-rodrigues — APPROVED** [review]

**Comment by eduardo-rodrigues** [comment]
@all-contributors please add @manuelfs for code

**Pull request merged**
