### PR TITLE
Add isort to pre-commit hooks

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
To better follow Scikit-HEP guidelines :-).

### CODE REVIEW

**Comment by henryiii** [comment]
Okay if I turn off sourcery?

Please add:

```toml
[tool.isort]
profile = "black"
```

to `pyproject.toml`, so this will be black-ready. (unless it's already there)

**Comment by henryiii** [comment]
(This honestly looks like the black style for isort already)

**Comment by eduardo-rodrigues** [comment]
> Okay if I turn off sourcery?

Yep!

> Please add:
> 
> ```toml
> [tool.isort]
> profile = "black"
> ```
> 
> to `pyproject.toml`, so this will be black-ready. (unless it's already there)

That's already there - https://github.com/scikit-hep/decaylanguage/blob/master/pyproject.toml#L13-L15 - and why I did not commit that.

**Comment by eduardo-rodrigues** [comment]
> (This honestly looks like the black style for isort already)

Indeed, see my reply just above :D.

**Review by henryiii — APPROVED** [review]

**Comment by henryiii** [comment]
(You can remove `multi_line_output = 3`, that's part of the black profile)

**Pull request merged**
